# Setup
title:               Jung-Bin Wang
tagline:             'things speak by itself'
description:         'absorbing laten heat...'
url:                 https://wangjb.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jung-Bin Wang
  url:               https://wangjb.github.io
  email:             jbwangkenobi@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
